language: c
compiler:
    - clang
notifications:
    email:
        on_success: change
        on_failure: change
    slack:
        rooms: cznic:xNJmvHU2xu2aGtN7Y2eqHKoD
        on_success: change
        on_failure: change
    webhooks:
        urls: https://webhooks.gitter.im/e/66485d8f591942052faa
        on_success: always
        on_failure: always
env:
    global:
        - PKG_CONFIG_PATH="${HOME}/.local/lib/pkgconfig"
        - PATH="${HOME}/.local/bin:/usr/local/bin:${PATH}"
        - CFLAGS="${CFLAGS} -O0 -g -fPIC -DNDEBUG"
        - LD_LIBRARY_PATH="${HOME}/.local/lib"
        - secure: "OfAd7YOX7AETqcqtHB0tMeMWOF8GgjEcqd+AVSj4ZPc/WqWQc9nqpch39ApadHf6kXfSXAlhHhIvQmDwLUoPORq7FAk37VIF2aNBCHBJ+H5S18VEiKdPM1f4fJYlq8akgpR1K7jbzpckht86g1BrzlEzCj8zXrnlRrHOPYEzpWk="
before_script:
    - ./scripts/bootstrap-depends.sh ${HOME}/.local
script:
    - make
sudo: false
cache:
    directories:
    - ${HOME}/.local
    - ${HOME}/.cache/pip

addons:
  coverity_scan:
    project:
      name: "CZ-NIC/knot-resolver"
      description: "Build submitted via Travis CI"
    notification_email: marek.vavrusa@nic.cz
    build_command:   "make"
    branch_pattern: coverity_scan
